//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Umbraco.Headless.Client.Net.Tests.Management {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RelationTypeServiceJson {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RelationTypeServiceJson() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Umbraco.Headless.Client.Net.Tests.Management.RelationTypeServiceJson", typeof(RelationTypeServiceJson).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;name&quot;: &quot;Relate Document On Copy&quot;,
        ///  &quot;alias&quot;: &quot;relateDocumentOnCopy&quot;,
        ///  &quot;isBidirectional&quot;: true,
        ///  &quot;parentObjectType&quot;: &quot;Unknown&quot;,
        ///  &quot;childObjectType&quot;: &quot;Unknown&quot;,
        ///  &quot;_createDate&quot;: &quot;0001-01-01T00:00:00Z&quot;,
        ///  &quot;_id&quot;: &quot;4cbeb612-e689-3563-b755-bf3ede295433&quot;,
        ///  &quot;_updateDate&quot;: &quot;0001-01-01T00:00:00Z&quot;
        ///}.
        /// </summary>
        internal static string ByAlias {
            get {
                return ResourceManager.GetString("ByAlias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;_links&quot;: {
        ///        &quot;self&quot;: {
        ///            &quot;href&quot;: &quot;https://api.umbraco.io/relation/type&quot;
        ///        },
        ///        &quot;relationtypes&quot;: [
        ///            {
        ///                &quot;href&quot;: &quot;https://api.umbraco.io/relation/type/relateDocumentOnCopy&quot;
        ///            },
        ///            {
        ///                &quot;href&quot;: &quot;https://api.umbraco.io/relation/type/relateParentDocumentOnDelete&quot;
        ///            },
        ///            {
        ///                &quot;href&quot;: &quot;https://api.umbraco.io/relation/type/relateParentMediaFolderOnDelete&quot;
        ///            }
        ///        ]
        ///    },
        ///    &quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetAll {
            get {
                return ResourceManager.GetString("GetAll", resourceCulture);
            }
        }
    }
}
