//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Umbraco.Headless.Client.Net.Tests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MediaDeliveryJson {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MediaDeliveryJson() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Umbraco.Headless.Client.Net.Tests.MediaDeliveryJson", typeof(MediaDeliveryJson).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;_totalItems&quot;: 1,
        ///    &quot;_totalPages&quot;: 1,
        ///    &quot;_page&quot;: 1,
        ///    &quot;_pageSize&quot;: 10,
        ///    &quot;_links&quot;: {
        ///        &quot;self&quot;: {
        ///            &quot;href&quot;: &quot;https://cdn.umbraco.io/media/6d986832-fb11-4d65-b2ae-0d7742f27a19/children?page=1&quot;
        ///        },
        ///        &quot;page&quot;: {
        ///            &quot;href&quot;: &quot;https://cdn.umbraco.io/media/{id}/children{?page,pageSize}&quot;,
        ///            &quot;templated&quot;: true
        ///        },
        ///        &quot;root&quot;: {
        ///            &quot;href&quot;: &quot;https://cdn.umbraco.io/media&quot;
        ///        },
        ///        &quot;media&quot;: {
        ///            &quot;href&quot;: &quot;https://cdn.umbraco [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetChildrenByParentId {
            get {
                return ResourceManager.GetString("GetChildrenByParentId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;_creatorName&quot;: &quot;Morten Christensen&quot;,
        ///    &quot;_url&quot;: &quot;&quot;,
        ///    &quot;_writerName&quot;: &quot;Morten Christensen&quot;,
        ///    &quot;_hasChildren&quot;: true,
        ///    &quot;_level&quot;: 1,
        ///    &quot;_createDate&quot;: &quot;2019-09-13T09:00:59.91Z&quot;,
        ///    &quot;_id&quot;: &quot;6d986832-fb11-4d65-b2ae-0d7742f27a19&quot;,
        ///    &quot;_updateDate&quot;: &quot;2019-09-13T09:00:59.91Z&quot;,
        ///    &quot;_links&quot;: {
        ///        &quot;self&quot;: {
        ///            &quot;href&quot;: &quot;https://cdn.umbraco.io/media/6d986832-fb11-4d65-b2ae-0d7742f27a19&quot;
        ///        },
        ///        &quot;root&quot;: {
        ///            &quot;href&quot;: &quot;https://cdn.umbraco.io/media&quot;
        ///        },
        ///        &quot;chi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetMediaByIdFolder {
            get {
                return ResourceManager.GetString("GetMediaByIdFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;_creatorName&quot;: &quot;Morten Christensen&quot;,
        ///    &quot;_url&quot;: &quot;https://media.umbraco.io/media/l3ifqpfg/chewbacca.png&quot;,
        ///    &quot;_writerName&quot;: &quot;Morten Christensen&quot;,
        ///    &quot;_hasChildren&quot;: false,
        ///    &quot;_level&quot;: 2,
        ///    &quot;_createDate&quot;: &quot;2019-09-13T09:01:05.13Z&quot;,
        ///    &quot;_id&quot;: &quot;3c485159-99a6-44e4-a5f4-576253e0fda5&quot;,
        ///    &quot;_updateDate&quot;: &quot;2019-09-13T09:01:05.13Z&quot;,
        ///    &quot;_links&quot;: {
        ///        &quot;self&quot;: {
        ///            &quot;href&quot;: &quot;https://cdn.umbraco.io/media/3c485159-99a6-44e4-a5f4-576253e0fda5&quot;
        ///        },
        ///        &quot;root&quot;: {
        ///            &quot;href&quot;:  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetMediaByIdMediaItem {
            get {
                return ResourceManager.GetString("GetMediaByIdMediaItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;_links&quot;: {
        ///        &quot;self&quot;: {
        ///            &quot;href&quot;: &quot;https://cdn.umbraco.io/media&quot;
        ///        },
        ///        &quot;children&quot;: {
        ///            &quot;href&quot;: &quot;https://cdn.umbraco.io/media/{id}/children{?page,pageSize}&quot;,
        ///            &quot;templated&quot;: true
        ///        },
        ///        &quot;media&quot;: [
        ///            {
        ///                &quot;href&quot;: &quot;https://cdn.umbraco.io/media/{id}&quot;,
        ///                &quot;templated&quot;: true
        ///            },
        ///            {
        ///                &quot;href&quot;: &quot;https://cdn.umbraco.io/media/6d986832-fb11-4d65-b2ae-0d7742f27a19&quot;
        ///            },
        ///      [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetRoot {
            get {
                return ResourceManager.GetString("GetRoot", resourceCulture);
            }
        }
    }
}
