//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Umbraco.Headless.Client.Net.Tests.Management.Models {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MediaJson {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MediaJson() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Umbraco.Headless.Client.Net.Tests.Management.Models.MediaJson", typeof(MediaJson).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {&quot;contentTypeAlias&quot;:&quot;product&quot;,&quot;name&quot;:{&quot;en-US&quot;:&quot;Biker Jacket&quot;,&quot;da&quot;:&quot;Biker Jakke&quot;},&quot;productName&quot;:{&quot;en-US&quot;:&quot;Biker Jacket&quot;,&quot;da&quot;:&quot;Biker Jakke&quot;},&quot;price&quot;:{&quot;en-US&quot;:&quot;199&quot;,&quot;da&quot;:&quot;1399&quot;},&quot;description&quot;:{&quot;en-US&quot;:&quot;Donec rutrum congue leo eget malesuada. Vivamus suscipit tortor eget felis porttitor volutpat.&quot;,&quot;da&quot;:&quot;Donec rutrum congue leo eget malesuada. Vivamus suscipit tortor eget felis porttitor volutpat.&quot;},&quot;sku&quot;:{&quot;$invariant&quot;:&quot;UMB-BIKER-JACKET&quot;},&quot;photos&quot;:{&quot;$invariant&quot;:&quot;umb://media/55514845b8bd487cb3709724852fd6bb&quot;},&quot;fe [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Json {
            get {
                return ResourceManager.GetString("Json", resourceCulture);
            }
        }
    }
}
